FROM node:17-alpine
WORKDIR /app
COPY ./package.json ./
COPY ./package-lock.json ./
RUN npm ci
RUN chown -R node.node /app
COPY . .
EXPOSE 3000
CMD ["npm", "run", "build"]
CMD ["npm", "run", "preview"]
