FROM node:17-alpine
WORKDIR /app
COPY ./package.json ./
COPY ./package-lock.json ./
RUN chown -R node:node /app/node_modules
RUN npm ci
COPY . .
RUN chmod 777 /app/node_modules
EXPOSE 3000
CMD ["npm", "run", "build"]
CMD ["npm", "run", "preview"]
