FROM node:18

WORKDIR /app
COPY ./package.json ./
COPY ./package-lock.json ./
RUN mkdir -p /app/node_modules
RUN chown -R node:node /app/node_modules
RUN npm ci
RUN npm install -g nodemon

COPY . .
EXPOSE 3001
CMD ["npm", "run", "dev"]
